### ISSUE TITLE
REVIEW: logging

### ISSUE THREAD

**Issue by kares** [WURFL/logstash-filter-wurfl#1]
1. could we get rid of the 'testing' log.error lines [here](https://github.com/WURFL/logstash-filter-wurfl/blob/0488f67/src/main/java/com/scientiamobile/logstash/WurflDeviceDetection.java#L38-L39)
   feel free to log at a `debug` level e.g. `logger.debug("initialized wm-client: {}", wmClient);`

2. would be nice to log a [dropped event and possibly print trace using logger not system err](https://github.com/WURFL/logstash-filter-wurfl/blob/0488f67/src/main/java/com/scientiamobile/logstash/WurflDeviceDetection.java#L123-L126) e.g.
```java
            } catch (WmException e) {
                logger.error("dropping event " + event + " due " + e, e); // filter prefix will be added by LS
            }
```

**Comment by andreacastello** [comment]
@kares if it's OK, I'll close the issue.

**Comment by andreacastello** [comment]
@kares Hi, any news about this?

**Comment by andreacastello** [comment]
Hi, @kares if you have no further suggestions, I'll close this issue today.

**Comment by kares** [comment]
LGTM, thanks
